

from typing import (
    Any,
    Awaitable,
    Callable,
    Dict,
    List,
    Literal,
    Optional,
    Tuple,
    Type,
    Union,
)

import asyncio, os
from uvicorn.config import (
        LoopSetupType,
        HTTPProtocolType,
        WSProtocolType,
        LifespanType,
        LOGGING_CONFIG,
        InterfaceType,
        SSL_PROTOCOL_VERSION,
        ssl,

    )


UVICORN_CONF_ALLOWED = {
    'app':( Union["ASGIApplication", Callable, str], None),
    'host':( str, "127.0.0.1"),
    'port':( int, 8000),
    'uds':( Optional[str], None),
    'fd':( Optional[int], None),
    'loop':( LoopSetupType, "auto"),
    'http':( Union[Type[asyncio.Protocol], HTTPProtocolType], "auto"),
    'ws':( Union[Type[asyncio.Protocol], WSProtocolType], "auto"),
    'ws_max_size':( int, 16 * 1024 * 1024),
    'ws_max_queue':( int, 32),
    'ws_ping_interval':( Optional[float], 20.0),
    'ws_ping_timeout':( Optional[float], 20.0),
    'ws_per_message_deflate':( bool, True),
    'lifespan':( LifespanType, "auto"),
    'env_file':( Optional[Union[str, os.PathLike]], None),
    'log_config':( Optional[Union[Dict[str, Any], str]], LOGGING_CONFIG),
    'log_level':( Optional[Union[str, int]], None),
    'access_log':( bool, True),
    'use_colors':( Optional[bool], None),
    'interface':( InterfaceType, "auto"),
    'reload':( bool, False),
    'reload_dirs':( Optional[Union[List[str], str]], None),
    'reload_delay':( float, 0.25),
    'reload_includes':( Optional[Union[List[str], str]], None),
    'reload_excludes':( Optional[Union[List[str], str]], None),
    'workers':( Optional[int], None),
    'proxy_headers':( bool, True),
    'server_header':( bool, True),
    'date_header':( bool, True),
    'forwarded_allow_ips':( Optional[Union[List[str], str]], None),
    'root_path':( str, ""),
    'limit_concurrency':( Optional[int], None),
    'limit_max_requests':( Optional[int], None),
    'backlog':( int, 2048),
    'timeout_keep_alive':( int, 5),
    'timeout_notify':( int, 30),
    'timeout_graceful_shutdown':( Optional[int], None),
    'callback_notify':( Optional[Callable[..., Awaitable[None]]], None),
    'ssl_keyfile':( Optional[str], None),
    'ssl_certfile':( Optional[Union[str, os.PathLike]], None),
    'ssl_keyfile_password':( Optional[str], None),
    'ssl_version':( int, SSL_PROTOCOL_VERSION),
    'ssl_cert_reqs':( int, ssl.CERT_NONE),
    'ssl_ca_certs':( Optional[str], None),
    'ssl_ciphers':( str, "TLSv1"),
    'headers':( Optional[List[Tuple[str, str]]], None),
    'factory':( bool, False),
    'h11_max_incomplete_event_size':( Optional[int], None),
}

